### PR TITLE
Use vdiffr

### PR DESCRIPTION
**Pull request by VEZY**
# Use vdiffr again

## Infos

This is a PR for using vdiffr again for comparing the resulting svgs for our example plots. It should be portable between OS, except maybe for fig.8 that uses ggrepel that is using random numbers and iterations.

### CODE REVIEW

**Comment by VEZY** [comment]
All right guys that's it it works ! See the action here: https://github.com/SticsRPacks/CroPlotR/actions/runs/5403625034 
Note that you can download the resulting comparison in the snapshot 😄 . 
Should we merge the pull request ? @sbuis @plecharpent

**Comment by VEZY** [comment]
Can one of you review and accept the PR ? This way we will have a good way of validating the PR !

**Review by plecharpent — APPROVED** [review]
Good job.
Perhaps next time replace R -e with Rscript -e 
for avoiding log pollution with R session info.

**Comment by plecharpent** [comment]
Should we delete the branch, can be done here in the pull request

**Comment by VEZY** [comment]
> Good job. Perhaps next time replace R -e with Rscript -e for avoiding log pollution with R session info.

Ho yes, totally forgot to do that. Don't delete the branch yet, I'll use `Rscript` and push again, then merge a second time.

**Comment by VEZY** [comment]
OK that's done, I deleted the branch. We should maybe test the functionality now if possible.

**Pull request merged**
